/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INexusBridge,
  INexusBridgeInterface,
} from "../../../contracts/interfaces/INexusBridge";

const _abi = [
  {
    inputs: [],
    name: "IncorrectAmount",
    type: "error",
  },
  {
    inputs: [],
    name: "IncorrectWithdrawalCredentials",
    type: "error",
  },
  {
    inputs: [],
    name: "NotDAO",
    type: "error",
  },
  {
    inputs: [],
    name: "NotNexus",
    type: "error",
  },
  {
    inputs: [],
    name: "StakingLimitExceeding",
    type: "error",
  },
  {
    inputs: [],
    name: "WrongRewardAmount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "rewardReceiver",
        type: "address",
      },
    ],
    name: "RewardsRedeemed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "slashing",
        type: "bool",
      },
    ],
    name: "RewardsUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "pubKey",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "withdrawalAddress",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
          {
            internalType: "bytes32",
            name: "depositRoot",
            type: "bytes32",
          },
        ],
        internalType: "struct INexusInterface.Validator[]",
        name: "_validators",
        type: "tuple[]",
      },
      {
        internalType: "uint256",
        name: "stakingLimit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "validatorCount",
        type: "uint256",
      },
    ],
    name: "depositValidatorNexus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "slashed",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "validatorCount",
        type: "uint256",
      },
    ],
    name: "updateRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INexusBridge__factory {
  static readonly abi = _abi;
  static createInterface(): INexusBridgeInterface {
    return new Interface(_abi) as INexusBridgeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INexusBridge {
    return new Contract(address, _abi, runner) as unknown as INexusBridge;
  }
}
