/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BridgeContract__factory } from "./BridgeContract__factory";
export { SSVToken__factory } from "./SSVToken__factory";
