/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace INexusInterface {
  export type ValidatorStruct = {
    pubKey: BytesLike;
    withdrawalAddress: BytesLike;
    signature: BytesLike;
    depositRoot: BytesLike;
  };

  export type ValidatorStructOutput = [
    pubKey: string,
    withdrawalAddress: string,
    signature: string,
    depositRoot: string
  ] & {
    pubKey: string;
    withdrawalAddress: string;
    signature: string;
    depositRoot: string;
  };
}

export interface NexusBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINT"
      | "DAO"
      | "DEPOSIT_CONTRACT"
      | "NEXUS_NETWORK"
      | "VALIDATOR_DEPOSIT"
      | "depositValidatorNexus"
      | "redeemRewards"
      | "stakingReturns"
      | "updateRewards"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RewardsRedeemed" | "RewardsUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DAO", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DEPOSIT_CONTRACT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NEXUS_NETWORK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VALIDATOR_DEPOSIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositValidatorNexus",
    values: [INexusInterface.ValidatorStruct[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemRewards",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingReturns",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateRewards",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DAO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEPOSIT_CONTRACT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NEXUS_NETWORK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VALIDATOR_DEPOSIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositValidatorNexus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingReturns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRewards",
    data: BytesLike
  ): Result;
}

export namespace RewardsRedeemedEvent {
  export type InputTuple = [amount: BigNumberish, rewardReceiver: AddressLike];
  export type OutputTuple = [amount: bigint, rewardReceiver: string];
  export interface OutputObject {
    amount: bigint;
    rewardReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsUpdatedEvent {
  export type InputTuple = [amount: BigNumberish, slashing: boolean];
  export type OutputTuple = [amount: bigint, slashing: boolean];
  export interface OutputObject {
    amount: bigint;
    slashing: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NexusBridge extends BaseContract {
  connect(runner?: ContractRunner | null): NexusBridge;
  waitForDeployment(): Promise<this>;

  interface: NexusBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINT: TypedContractMethod<[], [bigint], "view">;

  DAO: TypedContractMethod<[], [string], "view">;

  DEPOSIT_CONTRACT: TypedContractMethod<[], [string], "view">;

  NEXUS_NETWORK: TypedContractMethod<[], [string], "view">;

  VALIDATOR_DEPOSIT: TypedContractMethod<[], [bigint], "view">;

  depositValidatorNexus: TypedContractMethod<
    [
      _validators: INexusInterface.ValidatorStruct[],
      stakingLimit: BigNumberish,
      validatorCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  redeemRewards: TypedContractMethod<
    [amount: BigNumberish, toWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  stakingReturns: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        TotalRewardsEarned: bigint;
        RewardsRedeemed: bigint;
        Slashing: bigint;
      }
    ],
    "view"
  >;

  updateRewards: TypedContractMethod<
    [amount: BigNumberish, slashed: boolean, validatorCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DAO"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEPOSIT_CONTRACT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NEXUS_NETWORK"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VALIDATOR_DEPOSIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositValidatorNexus"
  ): TypedContractMethod<
    [
      _validators: INexusInterface.ValidatorStruct[],
      stakingLimit: BigNumberish,
      validatorCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeemRewards"
  ): TypedContractMethod<
    [amount: BigNumberish, toWallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakingReturns"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        TotalRewardsEarned: bigint;
        RewardsRedeemed: bigint;
        Slashing: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateRewards"
  ): TypedContractMethod<
    [amount: BigNumberish, slashed: boolean, validatorCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "RewardsRedeemed"
  ): TypedContractEvent<
    RewardsRedeemedEvent.InputTuple,
    RewardsRedeemedEvent.OutputTuple,
    RewardsRedeemedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsUpdated"
  ): TypedContractEvent<
    RewardsUpdatedEvent.InputTuple,
    RewardsUpdatedEvent.OutputTuple,
    RewardsUpdatedEvent.OutputObject
  >;

  filters: {
    "RewardsRedeemed(uint256,address)": TypedContractEvent<
      RewardsRedeemedEvent.InputTuple,
      RewardsRedeemedEvent.OutputTuple,
      RewardsRedeemedEvent.OutputObject
    >;
    RewardsRedeemed: TypedContractEvent<
      RewardsRedeemedEvent.InputTuple,
      RewardsRedeemedEvent.OutputTuple,
      RewardsRedeemedEvent.OutputObject
    >;

    "RewardsUpdated(uint256,bool)": TypedContractEvent<
      RewardsUpdatedEvent.InputTuple,
      RewardsUpdatedEvent.OutputTuple,
      RewardsUpdatedEvent.OutputObject
    >;
    RewardsUpdated: TypedContractEvent<
      RewardsUpdatedEvent.InputTuple,
      RewardsUpdatedEvent.OutputTuple,
      RewardsUpdatedEvent.OutputObject
    >;
  };
}
