/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as issvNetworkSol from "./ISSVNetwork.sol";
export type { issvNetworkSol };
export type { IDepositContract } from "./IDepositContract";
export type { INexusBridge } from "./INexusBridge";
export type { INexusInterface } from "./INexusInterface";
