/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nexusOwnableSol from "./NexusOwnable.sol";
export type { nexusOwnableSol };
import type * as nexusProxySol from "./NexusProxy.sol";
export type { nexusProxySol };
import type * as uupsUpgreadableSol from "./UUPSUpgreadable.sol";
export type { uupsUpgreadableSol };
